replicaCount: 1

image:
  repository: soumyakube/django-banking-app
  tag: latest
  pullPolicy: Always

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 80
  targetPort: 8000
  nodePort: 30080

config:
  debug: "False"
  allowedHosts: "*"

secret:
  djangoSecretKey: "change-this-banking-secret"

containerPort: 8000

resources:
  requests:
    cpu: 100m
    memory: 128Mi

  limits:
    cpu: 500m
    memory: 512Mi

probes:
  readiness:
    initialDelaySeconds: 10
    periodSeconds: 5

  liveness:
    initialDelaySeconds: 20
    periodSeconds: 10

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 999
  runAsGroup: 999
  fsGroup: 999

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  capabilities:
    drop:
      - ALL